version: 2

sources:
  - name: raw
    database: "{{ env_var('DBT_AUDIT_DB') }}"
    schema: raw
    tables:
      - name: policies
        description: Source table for policies
        columns:
          - name: policy_id
            description: Primary key for policy
            tests:
              - assert_column_not_null:
                  config:
                    store_failures: true
              - assert_column_unique:
                  config:
                    store_failures: true

          - name: policy_type
            description: Type of policy (Health, Life, Auto)
            tests:
              - expect_column_values_to_be_in_list:
                  values: ['Health', 'Life', 'Auto']
                  config:
                    store_failures: true

      - name: claims
        description: Source table for claims
        columns:
          - name: claim_id
            description: Primary key for claim
            tests:
              - assert_column_not_null:
                  config:
                    severity: warn
                    store_failures: true
              - assert_column_unique:
                  config:
                    store_failures: true

          - name: policy_id
            description: Foreign key to policy
            tests:
              - validate_foreign_key:
                  ref_model: "{{ ref('raw_policies') }}"
                  ref_column: policy_id
                  config:
                    store_failures: true

models:
  - name: sl_policies
    description: SL layer with lightly transformed policies
    columns:
      - name: policy_id
        tests:
          - assert_column_not_null:
              config:
                store_failures: true
          - assert_column_unique:
              config:
                store_failures: true

      - name: policy_type
        tests:
          - expect_column_values_to_be_in_list:
              values: ['Health', 'Life', 'Auto']
              config:
                store_failures: true


  - name: gl_policy_summary
    description: Business summary view of policies and claims
    columns:
      - name: policy_id
        description: Joined from policy
      - name: claim_id
        description: Joined from claims
